export type DataRefreshCadence = "monthly" | "quarterly" | "annual" | "release-calendar" | "manual-review";

export const officialDataSources = [
  {
    slug: "statcan-cpi",
    name: "Consumer Price Index",
    publisher: "Statistics Canada",
    table: "18-10-0004-01",
    url: "https://www.statcan.gc.ca/en/subjects-start/prices_and_price_indexes/consumer_price_indexes",
    cadence: "monthly" satisfies DataRefreshCadence,
    latestKnownPeriod: "April 2026",
    nextExpectedRelease: "2026-06-22",
    appAreas: ["inflation", "food inflation", "province CPI"],
  },
  {
    slug: "cra-tax-rates",
    name: "Federal and provincial income tax rates",
    publisher: "Canada Revenue Agency",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/individuals/frequently-asked-questions-individuals/canadian-income-tax-rates-individuals-current-previous-years.html",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "2026 tax year",
    nextExpectedRelease: "2027 tax year update",
    appAreas: ["tax-dollar", "province tax"],
  },
  {
    slug: "ircc-temporary-residents",
    name: "Temporary resident targets and permit holder stock",
    publisher: "Immigration, Refugees and Citizenship Canada",
    url: "https://www.canada.ca/en/immigration-refugees-citizenship/corporate/transparency/committees/cimm-dec-04-2025/temporary-resident-target.html",
    cadence: "quarterly" satisfies DataRefreshCadence,
    latestKnownPeriod: "September 30, 2025",
    nextExpectedRelease: "Monitor IRCC and StatCan quarterly releases",
    appAreas: ["population pressure", "students", "workers", "asylum"],
  },
  {
    slug: "statcan-population-estimates",
    name: "Population estimates by province and territory",
    publisher: "Statistics Canada",
    url: "https://www150.statcan.gc.ca/n1/en/type/data",
    cadence: "quarterly" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest quarterly release",
    nextExpectedRelease: "quarterly population estimates release cycle",
    appAreas: ["population pressure", "province growth", "interprovincial migration"],
  },
  {
    slug: "ircc-admissions",
    name: "Permanent resident admissions and immigration category tables",
    publisher: "Immigration, Refugees and Citizenship Canada",
    url: "https://www.canada.ca/en/immigration-refugees-citizenship/corporate/reports-statistics/statistics-open-data.html",
    cadence: "quarterly" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest IRCC open data release",
    nextExpectedRelease: "quarterly IRCC data refresh",
    appAreas: ["permanent residents", "refugees", "business immigration", "province immigration"],
  },
  {
    slug: "statcan-lfs",
    name: "Labour Force Survey",
    publisher: "Statistics Canada",
    url: "https://www.statcan.gc.ca/en/survey/household/3701",
    cadence: "monthly" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest monthly release",
    nextExpectedRelease: "monthly labour force release cycle",
    appAreas: ["jobs absorption", "youth unemployment", "population pressure"],
  },
  {
    slug: "statcan-income-survey",
    name: "Canadian Income Survey",
    publisher: "Statistics Canada",
    url: "https://www.statcan.gc.ca/en/survey/household/5200",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest income survey release",
    nextExpectedRelease: "annual income release cycle",
    appAreas: ["youth", "income", "rent burden", "disposable income", "affordability"],
  },
  {
    slug: "statcan-childcare",
    name: "Child care arrangements and costs",
    publisher: "Statistics Canada",
    url: "https://www.statcan.gc.ca/en/subjects-start/children_and_youth",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest childcare release",
    nextExpectedRelease: "annual childcare release cycle",
    appAreas: ["youth", "new families", "childcare", "family formation"],
  },
  {
    slug: "statcan-gdp-income-expenditure",
    name: "Gross domestic product by income and expenditure",
    publisher: "Statistics Canada",
    url: "https://www150.statcan.gc.ca/n1/daily-quotidien/260529/dq260529a-eng.htm",
    cadence: "quarterly" satisfies DataRefreshCadence,
    latestKnownPeriod: "Q1 2026",
    nextExpectedRelease: "2026-08-28",
    appAreas: ["GDP", "business investment", "household saving", "exports", "imports"],
  },
  {
    slug: "statcan-gdp-industry",
    name: "Gross domestic product by industry",
    publisher: "Statistics Canada",
    table: "36-10-0434-01",
    url: "https://www150.statcan.gc.ca/n1/daily-quotidien/260529/dq260529b-eng.htm",
    cadence: "monthly" satisfies DataRefreshCadence,
    latestKnownPeriod: "March 2026",
    nextExpectedRelease: "2026-06-30",
    appAreas: ["GDP by industry", "goods industries", "services industries", "sector breakdown"],
  },
  {
    slug: "statcan-international-trade",
    name: "Canadian international merchandise trade",
    publisher: "Statistics Canada",
    url: "https://www.statcan.gc.ca/en/subjects-start/international_trade",
    cadence: "monthly" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest monthly trade release",
    nextExpectedRelease: "monthly international trade release cycle",
    appAreas: ["trade", "exports", "imports", "trade partners", "sector exports"],
  },
  {
    slug: "statcan-interprovincial-trade",
    name: "Interprovincial trade and provincial economic accounts",
    publisher: "Statistics Canada",
    url: "https://www150.statcan.gc.ca/n1/en/type/data",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest provincial accounts release",
    nextExpectedRelease: "annual provincial accounts release cycle",
    appAreas: ["interprovincial trade", "province exports", "province imports", "industry GDP"],
  },
  {
    slug: "cmhc-housing",
    name: "Housing starts, completions, rental market",
    publisher: "CMHC",
    url: "https://www.cmhc-schl.gc.ca/",
    cadence: "monthly" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest CMHC release",
    nextExpectedRelease: "monthly release cycle",
    appAreas: ["housing", "rent", "supply"],
  },
  {
    slug: "budget-canada",
    name: "Federal budget and public accounts",
    publisher: "Government of Canada",
    url: "https://www.budget.canada.ca/",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest budget/public accounts",
    nextExpectedRelease: "annual budget cycle",
    appAreas: ["tax-dollar", "debt", "spending"],
  },
  {
    slug: "finance-fiscal-monitor",
    name: "Fiscal Monitor",
    publisher: "Department of Finance Canada",
    url: "https://www.canada.ca/en/department-finance/services/publications/fiscal-monitor/2026/03.html",
    cadence: "monthly" satisfies DataRefreshCadence,
    latestKnownPeriod: "April 2025 to March 2026",
    nextExpectedRelease: "monthly Fiscal Monitor release cycle",
    appAreas: ["government", "revenue", "expenses", "deficit", "public debt charges"],
  },
  {
    slug: "finance-major-transfers",
    name: "Major federal transfers",
    publisher: "Department of Finance Canada",
    url: "https://www.canada.ca/en/department-finance/programs/federal-transfers/major-federal-transfers.html",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "2026-27",
    nextExpectedRelease: "2027-28 transfer table update",
    appAreas: ["government", "transfers", "equalization", "CHT", "CST"],
  },
  {
    slug: "cihi-health-expenditure",
    name: "National health expenditure and health system indicators",
    publisher: "Canadian Institute for Health Information",
    url: "https://www.cihi.ca/en",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest CIHI health expenditure release",
    nextExpectedRelease: "annual CIHI release cycle",
    appAreas: ["health", "health spending", "wait times", "doctor access", "hospital capacity"],
  },
  {
    slug: "phac-chronic-disease",
    name: "Canadian Chronic Disease Surveillance System",
    publisher: "Public Health Agency of Canada",
    url: "https://health-infobase.canada.ca/ccdss/",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest CCDSS release",
    nextExpectedRelease: "annual chronic disease update cycle",
    appAreas: ["health", "diabetes", "cardiovascular disease", "respiratory disease", "mental health", "vision loss"],
  },
  {
    slug: "statcan-community-health",
    name: "Canadian Community Health Survey",
    publisher: "Statistics Canada",
    url: "https://www.statcan.gc.ca/en/survey/household/3226",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest CCHS release",
    nextExpectedRelease: "annual CCHS release cycle",
    appAreas: ["health", "risk factors", "doctor access", "mental health", "lifestyle indicators"],
  },
  {
    slug: "statcan-crime-justice",
    name: "Crime and justice statistics",
    publisher: "Statistics Canada",
    url: "https://www.statcan.gc.ca/en/subjects-start/crime_and_justice",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest crime release",
    nextExpectedRelease: "annual crime statistics release cycle",
    appAreas: ["quality of life", "crime", "safety", "violent crime"],
  },
  {
    slug: "statcan-quality-life",
    name: "Quality of Life Framework and wellbeing indicators",
    publisher: "Statistics Canada",
    url: "https://www160.statcan.gc.ca/index-eng.htm",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest quality-of-life indicator release",
    nextExpectedRelease: "quality-of-life indicator release cycle",
    appAreas: ["quality of life", "life satisfaction", "wellbeing", "commute", "social indicators"],
  },
  {
    slug: "canada-energy-regulator",
    name: "Canada Energy Regulator data and analysis",
    publisher: "Canada Energy Regulator",
    url: "https://www.cer-rec.gc.ca/en/data-analysis/",
    cadence: "monthly" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest CER data release",
    nextExpectedRelease: "energy dataset release cycle",
    appAreas: ["energy", "oil production", "gas production", "exports", "pipelines", "electricity"],
  },
  {
    slug: "nrcan-energy",
    name: "Energy facts and electricity data",
    publisher: "Natural Resources Canada",
    url: "https://natural-resources.canada.ca/energy",
    cadence: "annual" satisfies DataRefreshCadence,
    latestKnownPeriod: "latest energy facts release",
    nextExpectedRelease: "annual energy facts update",
    appAreas: ["electricity mix", "fuel prices", "energy use", "resources"],
  },
  {
    slug: "gaswizard-pump-prices",
    name: "Gas price predictions and city pump prices",
    publisher: "GasWizard.ca",
    url: "https://gaswizard.ca/price-history/",
    cadence: "manual-review" satisfies DataRefreshCadence,
    latestKnownPeriod: "GasWizard current city pages",
    nextExpectedRelease: "Monitor GasWizard city-page updates",
    appAreas: ["gas prices", "fuel affordability", "live pressure trackers"],
  },
];

export const refreshJobs = officialDataSources.map((source) => ({
  id: `refresh-${source.slug}`,
  sourceSlug: source.slug,
  name: `Refresh ${source.name}`,
  cadence: source.cadence,
  nextExpectedRelease: source.nextExpectedRelease,
  appAreas: source.appAreas,
}));
