import type { IndicatorCategorySlug } from "./categories";

export type MockIndicator = {
  slug: string;
  name: string;
  description: string;
  unit: string;
  categorySlug: IndicatorCategorySlug;
  frequency: "MONTHLY" | "QUARTERLY" | "ANNUAL";
  direction: "HIGHER_IS_BETTER" | "LOWER_IS_BETTER" | "NEUTRAL";
  sourceSlug: string;
  isHot?: boolean;
  isYouth?: boolean;
};

export const indicators: MockIndicator[] = [
  {
    slug: "gdp-per-capita",
    name: "GDP per capita",
    description: "Economic output per person, a key signal for whether prosperity is rising.",
    unit: "CAD",
    categorySlug: "economy",
    frequency: "ANNUAL",
    direction: "HIGHER_IS_BETTER",
    sourceSlug: "statistics-canada",
    isHot: true,
  },
  {
    slug: "productivity-growth",
    name: "Productivity growth",
    description: "Output per hour growth, one of Canada's most important long-run living standard indicators.",
    unit: "%",
    categorySlug: "economy",
    frequency: "ANNUAL",
    direction: "HIGHER_IS_BETTER",
    sourceSlug: "statistics-canada",
    isHot: true,
  },
  {
    slug: "unemployment-rate",
    name: "Unemployment rate",
    description: "Share of the labour force that is unemployed.",
    unit: "%",
    categorySlug: "economy",
    frequency: "MONTHLY",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "statistics-canada",
  },
  {
    slug: "youth-unemployment-rate",
    name: "Youth unemployment rate",
    description: "Unemployment rate for younger workers.",
    unit: "%",
    categorySlug: "youth",
    frequency: "MONTHLY",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "statistics-canada",
    isHot: true,
    isYouth: true,
  },
  {
    slug: "median-after-tax-income",
    name: "Median after-tax income",
    description: "Median after-tax income available to households.",
    unit: "CAD",
    categorySlug: "economy",
    frequency: "ANNUAL",
    direction: "HIGHER_IS_BETTER",
    sourceSlug: "statistics-canada",
    isYouth: true,
  },
  {
    slug: "food-inflation",
    name: "Food inflation",
    description: "Price change for food purchased by households.",
    unit: "%",
    categorySlug: "economy",
    frequency: "MONTHLY",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "statistics-canada",
    isHot: true,
  },
  {
    slug: "benchmark-home-price",
    name: "Benchmark home price",
    description: "Representative home price used to estimate affordability stress.",
    unit: "CAD",
    categorySlug: "housing",
    frequency: "MONTHLY",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "cmhc",
    isHot: true,
    isYouth: true,
  },
  {
    slug: "average-rent",
    name: "Average rent",
    description: "Average monthly rent estimate.",
    unit: "CAD/month",
    categorySlug: "housing",
    frequency: "MONTHLY",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "cmhc",
    isHot: true,
    isYouth: true,
  },
  {
    slug: "housing-completions",
    name: "Housing completions",
    description: "Completed housing units, used against population growth pressure.",
    unit: "units",
    categorySlug: "housing",
    frequency: "ANNUAL",
    direction: "HIGHER_IS_BETTER",
    sourceSlug: "cmhc",
    isHot: true,
  },
  {
    slug: "rent-to-income-ratio",
    name: "Rent-to-income ratio",
    description: "Estimated share of gross monthly income required for average rent.",
    unit: "%",
    categorySlug: "housing",
    frequency: "ANNUAL",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "cmhc",
    isHot: true,
    isYouth: true,
  },
  {
    slug: "population-growth",
    name: "Population growth",
    description: "Annual population growth rate.",
    unit: "%",
    categorySlug: "immigration",
    frequency: "ANNUAL",
    direction: "NEUTRAL",
    sourceSlug: "statistics-canada",
    isHot: true,
  },
  {
    slug: "non-permanent-residents",
    name: "Non-permanent residents",
    description: "Temporary residents, including work and study permit holders and asylum claimants.",
    unit: "people",
    categorySlug: "immigration",
    frequency: "QUARTERLY",
    direction: "NEUTRAL",
    sourceSlug: "statistics-canada",
    isHot: true,
  },
  {
    slug: "health-spending-per-person",
    name: "Health spending per person",
    description: "Total health expenditure per capita.",
    unit: "CAD",
    categorySlug: "health",
    frequency: "ANNUAL",
    direction: "NEUTRAL",
    sourceSlug: "cihi",
    isHot: true,
  },
  {
    slug: "family-doctor-access",
    name: "Family doctor access",
    description: "Share of residents reporting access to a regular primary care provider.",
    unit: "%",
    categorySlug: "health",
    frequency: "ANNUAL",
    direction: "HIGHER_IS_BETTER",
    sourceSlug: "cihi",
    isHot: true,
  },
  {
    slug: "diabetes-prevalence",
    name: "Diabetes prevalence",
    description: "Share of population living with diagnosed diabetes.",
    unit: "%",
    categorySlug: "health",
    frequency: "ANNUAL",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "phac",
    isHot: true,
  },
  {
    slug: "cardiovascular-disease-prevalence",
    name: "Cardiovascular disease prevalence",
    description: "Estimated share of population affected by cardiovascular disease.",
    unit: "%",
    categorySlug: "health",
    frequency: "ANNUAL",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "phac",
  },
  {
    slug: "debt-service-cost",
    name: "Debt service cost",
    description: "Government interest cost pressure.",
    unit: "CAD billions",
    categorySlug: "government",
    frequency: "ANNUAL",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "open-government-canada",
    isHot: true,
  },
  {
    slug: "health-spending-share",
    name: "Health spending share",
    description: "Share of program spending allocated to health.",
    unit: "%",
    categorySlug: "government",
    frequency: "ANNUAL",
    direction: "NEUTRAL",
    sourceSlug: "open-government-canada",
  },
  {
    slug: "exports-total",
    name: "Total exports",
    description: "Goods and services sold outside the province or country.",
    unit: "CAD billions",
    categorySlug: "trade",
    frequency: "ANNUAL",
    direction: "HIGHER_IS_BETTER",
    sourceSlug: "statistics-canada",
  },
  {
    slug: "oil-gas-production-index",
    name: "Oil and gas production index",
    description: "Index of oil and gas output strength by province.",
    unit: "index",
    categorySlug: "energy",
    frequency: "ANNUAL",
    direction: "HIGHER_IS_BETTER",
    sourceSlug: "canada-energy-regulator",
    isHot: true,
  },
  {
    slug: "electricity-price",
    name: "Electricity price",
    description: "Representative electricity cost for households.",
    unit: "cents/kWh",
    categorySlug: "energy",
    frequency: "ANNUAL",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "canada-energy-regulator",
  },
  {
    slug: "childcare-cost",
    name: "Childcare cost",
    description: "Representative monthly childcare cost for young families.",
    unit: "CAD/month",
    categorySlug: "youth",
    frequency: "ANNUAL",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "statistics-canada",
    isYouth: true,
  },
  {
    slug: "violent-crime-rate",
    name: "Violent crime rate",
    description: "Reported violent crime rate.",
    unit: "per 100,000",
    categorySlug: "quality-of-life",
    frequency: "ANNUAL",
    direction: "LOWER_IS_BETTER",
    sourceSlug: "statistics-canada",
  },
  {
    slug: "life-satisfaction",
    name: "Life satisfaction",
    description: "Reported life satisfaction score.",
    unit: "score",
    categorySlug: "quality-of-life",
    frequency: "ANNUAL",
    direction: "HIGHER_IS_BETTER",
    sourceSlug: "statistics-canada",
    isYouth: true,
  },
];
