import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { getPolicyFeed } from "@/lib/policy-data";
export const dynamic = "force-dynamic";
export default async function PolicyDetail({ params }: { params: Promise<{ id: string }> }) {
  const [{ id }, feed] = await Promise.all([params, getPolicyFeed()]);
  const bill = feed.bills.find((item) => item.id === id); if (!bill) { if (feed.status === "unavailable") return <AppShell><h1 className="text-3xl font-bold">Official bill record temporarily unavailable</h1><p className="mt-4">This page cannot verify a bill’s current status right now.</p><Link href="/policy" className="mt-4 inline-block underline">Return to the tracker</Link></AppShell>; notFound(); }
  const stages = [{ label: "Introduced", value: bill.introduced ?? "Date not supplied", verified: Boolean(bill.introduced) }, { label: "Latest completed major stage", value: bill.stage, verified: bill.stage !== "Stage not supplied" }, { label: "Royal assent", value: bill.assent ?? "Not confirmed in this record", verified: Boolean(bill.assent) }, { label: "In force", value: "Check commencement provisions and orders", verified: false }, { label: "Delivery & outcomes", value: "Requires program and outcome evidence", verified: false }];
  return <AppShell><Link href="/policy" className="font-bold text-teal-800">← All bills</Link><p className="cp-eyebrow mt-6">{bill.number} · official bill record</p><h1 className="mt-3 max-w-5xl text-4xl font-bold">{bill.title}</h1><p className="mt-4 text-lg">{bill.status}</p><ol className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{stages.map((stage, index) => <li key={stage.label} className={`cp-card ${stage.verified ? "border-teal-300" : "border-stone-200"}`}><p className="cp-eyebrow">Stage {index + 1} · {stage.verified ? "Official record loaded" : "Not verified here"}</p><h2 className="mt-3 text-lg font-bold">{stage.label}</h2><p className="mt-2 text-sm leading-6 text-stone-600">{stage.value}</p></li>)}</ol><section className="cp-card mt-6"><h2 className="text-2xl font-bold">What would this mean for me?</h2><p className="mt-3 leading-7">Before assuming a benefit or new obligation, check the bill text for eligibility, affected households, commencement dates and responsible departments. This tracker verifies legislative progress; it does not infer those details from the title.</p><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="font-bold">Sponsor</dt><dd className="mt-1 text-stone-600">{bill.sponsor}</dd></div><div><dt className="font-bold">Next evidence to check</dt><dd className="mt-1 text-stone-600">Legislative summary, official costing, regulations, program eligibility and implementation reporting.</dd></div></dl><a href={bill.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-11 items-center rounded-lg bg-teal-900 px-4 font-bold text-white">Open bill text, votes & official timeline ↗</a></section></AppShell>;
}
