"use client";
import { useState } from "react";
import { seriesDisplay, type LifeSeries } from "@/lib/life-series";

export function SeriesTrend({ points, unit, title }: { points: { period: string; value: number }[]; unit: string; title: string }) {
  if (points.length < 2) return <p className="text-xs text-stone-500">Comparable history unavailable.</p>;
  const min = Math.min(...points.map((point) => point.value));
  const max = Math.max(...points.map((point) => point.value));
  const spread = max - min || 1;
  const coordinates = points.map((point, index) => `${35 + index / (points.length - 1) * 290},${92 - (point.value - min) / spread * 66}`).join(" ");
  return <div className="mt-4"><svg viewBox="0 0 350 120" role="img" aria-label={`${title}: ${points[0].period} to ${points.at(-1)!.period}; range ${seriesDisplay(min, unit)} to ${seriesDisplay(max, unit)}.`} className="w-full"><title>{title}</title><line x1="35" x2="325" y1="92" y2="92" stroke="#d6d3d1" /><text x="0" y="24" fontSize="10" fill="#57534e">{seriesDisplay(max, unit)}</text><text x="0" y="109" fontSize="10" fill="#57534e">{seriesDisplay(min, unit)}</text><polyline points={coordinates} fill="none" stroke="#0f766e" strokeWidth="2.5" strokeLinejoin="round" /></svg><div className="flex justify-between text-[10px] text-stone-500"><span>{points[0].period}</span><span>{points.at(-1)!.period}</span></div><p className="mt-1 text-[10px] text-stone-500">Trend axis shows the observed range; it does not start at zero.</p></div>;
}
export function LifeSeriesBoard({ series, title = "The evidence behind everyday life" }: { series: LifeSeries[]; title?: string }) {
  const [geography, setGeography] = useState("Canada");
  const geographies = [...new Set(series.flatMap((item) => item.rows.map((row) => row.geography.replace("Canada (excluding territories)", "Canada"))))];
  return <section className="py-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="cp-eyebrow">Official observations · actual cohorts</p><h2 className="mt-2 text-3xl font-bold">{title}</h2></div><label className="text-sm font-semibold">Place<select value={geography} onChange={(event) => setGeography(event.target.value)} className="cp-select mt-2 block min-w-48">{[...new Set(["Canada", ...geographies])].map((place) => <option key={place}>{place}</option>)}</select></label></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{series.map((item) => {
    const row = item.rows.find((entry) => entry.geography === geography || (geography === "Canada" && entry.geography === "Canada (excluding territories)"));
    const last = row?.points.at(-1); const previous = row?.points.at(-2); const change = last && previous ? last.value - previous.value : null;
    return <article key={item.id} className="rounded-2xl border border-stone-200 bg-white text-stone-950 p-5"><p className="cp-eyebrow">{item.cadence} · {item.cohort}</p><h3 className="mt-3 text-xl font-bold">{item.title}</h3><p className="mt-4 font-mono text-3xl font-bold">{last ? seriesDisplay(last.value, item.unit) : "Not available"}</p><p className="mt-2 text-xs text-stone-600">{last ? `${row!.geography} · data period ${last.period}` : `No verified series loaded for ${geography}`}</p>{change !== null ? <p className="mt-3 text-sm font-semibold text-teal-800">{change > 0 ? "+" : ""}{change.toFixed(1)} {item.unit === "%" ? "percentage points" : item.unit} since {previous!.period}</p> : null}{row ? <SeriesTrend points={row.points} unit={item.unit} title={`${item.title}, ${geography}`} /> : null}<p className="mt-4 text-sm leading-6">{item.implication}</p><details className="mt-3 text-sm"><summary className="cursor-pointer font-bold text-teal-800">Coverage & limitations</summary><p className="mt-2 leading-6 text-stone-600">{item.limitation}</p></details>{row ? <details className="mt-3 text-sm"><summary className="cursor-pointer font-bold text-teal-800">View data table</summary><div className="mt-2 max-h-56 overflow-auto"><table className="w-full text-left text-xs"><caption className="sr-only">{item.title} observations</caption><thead><tr><th className="p-2">Period</th><th className="p-2">{item.unit}</th></tr></thead><tbody>{[...row.points].reverse().map((point) => <tr key={point.period} className="border-t"><td className="p-2">{point.period}</td><td className="p-2">{seriesDisplay(point.value, item.unit)}</td></tr>)}</tbody></table></div></details> : null}<a href={item.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center text-sm font-bold text-teal-800">Statistics Canada source ↗</a></article>;
  })}</div><p className="mt-4 text-xs leading-6 text-stone-500">Different topics have different publication schedules. A current source check does not make an annual observation real-time. Charts use separate scales and retain each series’ actual cohort and period.</p></section>;
}
