"use client";
import { useState } from "react";
import Link from "next/link";
import type { StatCanCpiSnapshot } from "@/lib/statcan-cpi";
import type { LifeSeries } from "@/lib/life-series";
import { SeriesTrend } from "@/components/life-series-board";
export function MoneyExplorer({ cpi, wages }: { cpi: StatCanCpiSnapshot | null; wages?: LifeSeries }) {
  const [foodBudget, setFoodBudget] = useState(400); const [otherBudget, setOtherBudget] = useState(1000);
  const foodRate = cpi?.canada.food.yearOverYearPct; const headlineRate = cpi?.canada.allItems.yearOverYearPct;
  const impact = cpi ? foodBudget * foodRate! / 100 + otherBudget * headlineRate! / 100 : null;
  const wagePoints = wages?.rows.find((row) => row.geography === "Canada")?.points ?? [];
  const prices = cpi?.priceHistory ?? [];
  const aligned = prices.flatMap((price) => { const wage = wagePoints.find((point) => point.period.slice(0, 7) === price.period.slice(0, 7)); return wage ? [{ period: price.period.slice(0, 7), wage: wage.value, price: price.value }] : []; });
  const baseline = aligned[0];
  const indexedWages = baseline && baseline.wage > 0 ? aligned.map((point) => ({ period: point.period, value: point.wage / baseline.wage * 100 })) : [];
  const indexedPrices = baseline && baseline.price > 0 ? aligned.map((point) => ({ period: point.period, value: point.price / baseline.price * 100 })) : [];
  const last = aligned.at(-1);
  const realChange = last && baseline && baseline.price > 0 && baseline.wage > 0 ? ((last.wage / baseline.wage) / (last.price / baseline.price) - 1) * 100 : null;
  return <div className="space-y-6"><section className="rounded-3xl bg-amber-50 p-6 sm:p-9"><p className="cp-eyebrow">My money · prices and purchasing power</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">The price tag and your pay need the same picture.</h1><p className="mt-4 max-w-3xl leading-7 text-stone-600">A lower inflation rate does not necessarily mean lower prices. Explore how costs have changed, then connect that change to a budget.</p></section>
    <section className="cp-card"><h2 className="text-2xl font-bold">What inflation does—and does not—say</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><p className="text-sm text-stone-600">All-items CPI, year over year</p><p className="mt-2 text-4xl font-bold">{headlineRate === undefined ? "Unavailable" : `${headlineRate.toFixed(1)}%`}</p></div><div><p className="text-sm text-stone-600">Food CPI, year over year</p><p className="mt-2 text-4xl font-bold">{foodRate === undefined ? "Unavailable" : `${foodRate.toFixed(1)}%`}</p></div></div><p className="mt-4 text-xs text-stone-500">{cpi ? `Statistics Canada · ${cpi.referencePeriod} · released ${cpi.releaseDate}` : "Official CPI observations could not be loaded; no substitute rate is used."}</p><p className="mt-4 text-sm leading-6">These rates compare price levels with a year earlier. When a positive rate falls, prices are still higher than a year ago—they are rising more slowly.</p>{cpi ? <a href={cpi.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center font-bold text-teal-800">Check CPI source & basket coverage ↗</a> : null}</section>
    <section className="cp-card"><p className="cp-eyebrow">Canada · young employees aged 15–24</p><h2 className="mt-2 text-2xl font-bold">Has median pay kept up with prices?</h2>{realChange !== null ? <><p className="mt-4 text-4xl font-bold text-teal-800">{realChange > 0 ? "+" : ""}{realChange.toFixed(1)}%</p><p className="mt-2 text-sm text-stone-600">Derived change in CPI-adjusted median hourly wage, {baseline!.period} to {last!.period}.</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><h3 className="font-bold">Median youth wage · base = 100</h3><SeriesTrend points={indexedWages} unit=" index" title="Youth wages rebased to 100" /></div><div><h3 className="font-bold">All-items prices · base = 100</h3><SeriesTrend points={indexedPrices} unit=" index" title="CPI rebased to 100" /></div></div><p className="mt-4 text-xs leading-6 text-stone-500">Both series start at 100 in the same matched month. Panels have separately labelled axes. Wages are unadjusted for seasonality and reflect the mix of young employees; this is not the pay rise of the same person.</p><details className="mt-4 text-sm"><summary className="cursor-pointer font-bold text-teal-800">Calculation & matched data</summary><p className="mt-2 leading-6">Real wage change = [(latest wage / starting wage) ÷ (latest CPI / starting CPI) − 1] × 100. Only matching months are included.</p><table className="mt-3 w-full text-left text-xs"><thead><tr><th className="p-2">Month</th><th className="p-2">Wage index</th><th className="p-2">Price index</th></tr></thead><tbody>{aligned.map((point, index) => <tr key={point.period} className="border-t"><td className="p-2">{point.period}</td><td className="p-2">{indexedWages[index].value.toFixed(1)}</td><td className="p-2">{indexedPrices[index].value.toFixed(1)}</td></tr>)}</tbody></table></details></> : <p className="mt-4 text-sm text-stone-600">Matched official wage and price history is unavailable. No purchasing-power change has been inferred.</p>}{wages ? <a href={wages.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center text-sm font-bold text-teal-800">Official wage series ↗</a> : null}</section>
    <section className="cp-card"><p className="cp-eyebrow">Illustrative spending scenario</p><h2 className="mt-2 text-2xl font-bold">Translate the rate into dollars</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Monthly food spending a year ago<input type="number" min="0" max="100000" value={foodBudget} onChange={(event) => setFoodBudget(Math.max(0, Math.min(100000, Number(event.target.value) || 0)))} className="cp-input mt-2 w-full" /></label><label className="text-sm font-semibold">Other monthly spending a year ago<input type="number" min="0" max="100000" value={otherBudget} onChange={(event) => setOtherBudget(Math.max(0, Math.min(100000, Number(event.target.value) || 0)))} className="cp-input mt-2 w-full" /></label></div><p className="mt-5 text-3xl font-bold" aria-live="polite">{impact === null ? "Official rates unavailable" : `${impact < 0 ? "−" : "+"}$${Math.abs(impact).toFixed(0)} /month`}</p><p className="mt-3 text-sm leading-6 text-stone-600">Applies food CPI to the first input and all-items CPI as an approximate proxy for other spending. This is not a personal inflation index or a forecast. Actual categories, quantities and bills can differ.</p><Link href="/my-life" className="mt-4 inline-flex min-h-11 items-center font-bold text-teal-800">Build the complete monthly budget →</Link></section>
  </div>;
}
