"use client";
import { useState } from "react";
import Link from "next/link";
import { calculateBudget, type BudgetInputs } from "@/lib/budget";
import { ShareStatButton } from "@/components/share-stat-button";
export type RentalChoice = { name: string; rent: number; previousRent: number; vacancy: number; period: string; sourceUrl: string };
const money = (value: number) => value.toLocaleString("en-CA", { style: "currency", currency: "CAD", maximumFractionDigits: 0 });
export function MoveOutBudget({ markets, initialPlace }: { markets: RentalChoice[]; initialPlace?: string }) {
  const initial = markets.find((market) => market.name === initialPlace) ?? markets.find((market) => /Ottawa/i.test(market.name)) ?? markets[0];
  const [place, setPlace] = useState(initial?.name ?? "Custom rent");
  const [comparePlace, setComparePlace] = useState(markets.find((market) => /Calgary/i.test(market.name))?.name ?? markets[1]?.name ?? "");
  const [input, setInput] = useState<BudgetInputs>({ takeHome: 3500, rent: initial?.rent ?? 0, peopleSharing: 1, groceries: 400, transport: 150, utilities: 150, debt: 0, other: 250, savings: 300 });
  const [customRent, setCustomRent] = useState(false);
  const budget = calculateBudget(input); const market = markets.find((item) => item.name === place); const compare = markets.find((item) => item.name === comparePlace);
  const otherBudget = compare ? calculateBudget({ ...input, rent: compare.rent }) : null;
  function change(key: keyof BudgetInputs, raw: string) { const number = Number(raw); setInput((current) => ({ ...current, [key]: Number.isFinite(number) ? Math.min(100000, Math.max(key === "peopleSharing" ? 1 : 0, number)) : 0 })); if (key === "rent") setCustomRent(true); }
  function selectPlace(name: string) { const selected = markets.find((item) => item.name === name); setPlace(name); if (selected) setInput((current) => ({ ...current, rent: selected.rent })); setCustomRent(false); }
  const fields: { key: keyof BudgetInputs; label: string }[] = [{ key: "takeHome", label: "Monthly take-home income (after tax)" }, { key: "rent", label: "Total monthly rent for the home" }, { key: "peopleSharing", label: "People splitting rent equally" }, { key: "groceries", label: "Your groceries" }, { key: "transport", label: "Your transport" }, { key: "utilities", label: "Your utilities & internet" }, { key: "debt", label: "Your debt payments" }, { key: "other", label: "Your other essentials" }, { key: "savings", label: "Your savings goal" }];
  return <div className="space-y-6"><section className="rounded-3xl bg-teal-950 p-6 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-widest text-teal-200">My life · interactive scenario</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Can I afford to move out?</h1><p className="mt-4 max-w-3xl leading-7 text-teal-100">Start with a surveyed rent, enter the money you actually bring home, and see what remains for life. Change any expense to match your situation.</p></section>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-stone-200 bg-white text-stone-950 p-5 sm:p-7"><h2 className="text-2xl font-bold">Build your monthly picture</h2><label className="mt-5 block text-sm font-bold">City or province<select className="cp-select mt-2 w-full" value={place} onChange={(event) => selectPlace(event.target.value)}>{!markets.length ? <option>Custom rent</option> : markets.map((item) => <option key={item.name}>{item.name}</option>)}</select></label><p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-900">{market ? `CMHC ${market.period}: average two-bedroom purpose-built rent across existing and new structures. This is not an asking-rent quote. Edit rent using a real listing for a new lease.` : "The official rental source is unavailable. Enter a rent from a listing; no official value has been substituted."}</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields.map(({ key, label }) => <label key={key} className="text-sm font-semibold">{label}<input className="cp-input mt-2 w-full" type="number" min={key === "peopleSharing" ? 1 : 0} max={100000} step={key === "peopleSharing" ? 1 : 10} value={input[key]} onChange={(event) => change(key, event.target.value)} /></label>)}</div><p className="mt-5 text-xs leading-6 text-stone-500">Income and non-rent expenses are editable example assumptions, not official household averages. No tax liability is inferred. Your budget inputs stay in this page and are excluded from sharing.</p></section>
      <section className="rounded-2xl border border-stone-200 bg-white text-stone-950 p-5 sm:p-7" aria-live="polite"><p className="cp-eyebrow">After essentials & your savings goal</p><h2 className={`mt-3 font-mono text-5xl font-bold ${budget.remaining < 0 ? "text-rose-700" : "text-teal-800"}`}>{money(budget.remaining)}<span className="ml-2 text-sm text-stone-500">/month</span></h2><p className="mt-3 text-sm leading-6 text-stone-600">{budget.remaining < 0 ? "Your assumptions exceed take-home income. Try a different rent, shared housing, or expense plan." : "This is the balance under your inputs, before unlisted costs and unexpected bills."}</p><div className="mt-6 space-y-3"><div className="flex justify-between font-bold"><span>Take-home income</span><span>{money(budget.takeHome)}</span></div>{budget.expenses.map((expense) => <div key={expense.label}><div className="flex justify-between gap-3 text-sm"><span>{expense.label}</span><span className="font-mono">−{money(expense.value)}</span></div><div className="mt-1 h-2 rounded bg-stone-100"><div className="h-full rounded bg-teal-600" style={{ width: `${budget.takeHome > 0 ? Math.min(100, expense.value / budget.takeHome * 100) : 0}%` }} /></div></div>)}</div><p className="mt-4 text-xs text-stone-500">Bars show each expense as a share of your take-home income.</p><div className="mt-6 grid grid-cols-2 gap-4 border-y py-4"><div><p className="text-xs text-stone-500">Rent / take-home pay</p><p className="mt-1 text-2xl font-bold">{budget.rentShare === null ? "No income entered" : `${budget.rentShare.toFixed(0)}%`}</p></div><div><p className="text-xs text-stone-500">Rent basis</p><p className="mt-1 text-sm font-bold">{customRent ? "Your custom rent" : market ? `CMHC · ${market.period}` : "Your input"}</p></div></div>{market ? <a href={market.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center text-sm font-bold text-teal-800">Open the rental source ↗</a> : null}</section></div>
    {compare && otherBudget ? <section className="rounded-2xl border border-teal-200 bg-teal-50 text-stone-950 p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="cp-eyebrow">Same assumptions · different surveyed rent</p><h2 className="mt-2 text-2xl font-bold">What changes if I move?</h2></div><label className="text-sm font-semibold">Compare with<select className="cp-select mt-2 block" value={comparePlace} onChange={(event) => setComparePlace(event.target.value)}>{markets.map((item) => <option key={item.name}>{item.name}</option>)}</select></label></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-white text-stone-950 p-4"><h3 className="font-bold">{place}</h3><p className="mt-2 text-3xl font-bold">{money(budget.remaining)}</p><p className="mt-1 text-xs">Monthly balance · {customRent ? "custom rent" : market?.period}</p></div><div className="rounded-xl bg-white text-stone-950 p-4"><h3 className="font-bold">{compare.name}</h3><p className="mt-2 text-3xl font-bold">{money(otherBudget.remaining)}</p><p className="mt-1 text-xs">Monthly balance · CMHC {compare.period}</p></div></div><p className="mt-4 text-sm leading-6">Rent alone changes the monthly balance by {money(otherBudget.remaining - budget.remaining)}. This comparison holds income and all non-rent costs constant; moving, tax, wage and service differences are not included.</p><p className="mt-3 text-xs leading-6 text-stone-600">New-tenant rents are a separate measure. Canada Pulse currently imports the surveyed overall average; it does not label it as a new-lease price.</p></section> : null}
    <div className="flex flex-wrap gap-4"><ShareStatButton variant="light" url="/my-life" text="Explore a monthly move-out budget using dated CMHC rent evidence and your own assumptions. This is an illustrative scenario, not a tax calculation or rental quote." title="Share the budget tool" /><Link href="/government" className="inline-flex min-h-11 items-center text-sm font-bold text-teal-800">Explore actual government spending →</Link></div>
  </div>;
}
