"use client";
import Link from "next/link";
import { useState } from "react";
import type { PolicyFeed } from "@/lib/policy-data";
export function PolicyExplorer({ feed }: { feed: PolicyFeed }) {
  const [query, setQuery] = useState(""); const [topic, setTopic] = useState("All topics"); const [limit, setLimit] = useState(18);
  const visible = feed.bills.filter((bill) => (topic === "All topics" || bill.topics.includes(topic)) && `${bill.number} ${bill.title} ${bill.sponsor}`.toLowerCase().includes(query.toLowerCase()));
  return <section><div className="mt-6 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Search bills<input className="cp-input mt-2 w-full" placeholder="Housing, student, budget or bill number" value={query} onChange={(event) => { setQuery(event.target.value); setLimit(18); }} /></label><label className="text-sm font-bold">Life topic<select className="cp-select mt-2 w-full" value={topic} onChange={(event) => { setTopic(event.target.value); setLimit(18); }}>{["All topics", "Housing", "Money", "Work & education", "Health & community", "Future & environment"].map((item) => <option key={item}>{item}</option>)}</select></label></div><p className="mt-3 text-xs leading-6 text-stone-500">Topics are assigned from bill titles for discovery. They are not legal interpretations. Source checked {feed.checkedAt.slice(0, 10)}.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.slice(0, limit).map((bill) => <article key={bill.id} className="rounded-2xl border border-stone-200 bg-white p-5"><p className="cp-eyebrow">{bill.number} · Parliament {bill.parliament}-{bill.session}</p><h2 className="mt-3 text-lg font-bold leading-snug">{bill.title}</h2><p className={`mt-4 inline-block rounded-lg px-3 py-2 text-xs font-bold ${bill.assent ? "bg-teal-50 text-teal-900" : "bg-amber-50 text-amber-900"}`}>{bill.status}</p><p className="mt-3 text-sm leading-6 text-stone-600">Last completed major stage: {bill.stage}</p><p className="mt-2 text-xs text-stone-500">{bill.updated ? `Latest event: ${bill.updated}` : "No dated latest event supplied"}</p><Link className="mt-4 inline-flex min-h-11 items-center text-sm font-bold text-teal-800" href={`/policy/${bill.id}`}>Understand the stages →</Link></article>)}</div>{!visible.length ? <div className="mt-5 rounded-xl bg-amber-50 p-5">{feed.status === "unavailable" ? "The official bill feed could not be loaded. No bill status has been invented." : "No bills match this search."} <a className="font-bold underline" href="https://www.parl.ca/legisinfo/en/bills">Open LEGISinfo ↗</a></div> : null}{visible.length > limit ? <button className="mt-5 min-h-11 rounded-lg border border-teal-700 px-5 font-bold text-teal-800" onClick={() => setLimit((current) => current + 18)}>Show more bills</button> : null}</section>;
}
